[pytest]
# Configuración por defecto al ejecutar Pytest en consola
addopts = -v -s --tb=short

# Registro de marcas (tags) personalizadas para evitar warnings
markers =
    ai: Pruebas específicas de Inteligencia Artificial y LLMs
    api: Pruebas de integración de endpoints REST y seguridad OWASP
    cloud: Pruebas de conectores en la nube y manejo de secretos
    ui: Pruebas de interfaz web E2E con Playwright

# Indica dónde debe buscar Pytest los archivos de prueba
testpaths = tests